# test.py
import tempfile
import subprocess
import os
from pathlib import Path

latex_code = r"""
\documentclass[12pt]{article}
\begin{document}
Hello, this is a test PDF generated by pdflatex!
\end{document}
"""

def test_pdflatex():
    with tempfile.TemporaryDirectory() as tmpdir:
        tex_path = os.path.join(tmpdir, "test.tex")
        pdf_path = os.path.join(Path(""), "test.pdf")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(latex_code)
        try:
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", tex_path],
                # cwd=tmpdir,
                # stdout=subprocess.PIPE,
                # stderr=subprocess.PIPE,
                check=True
            )
            print(result)
            print("pdflatex ran successfully.")
            if os.path.exists(pdf_path):
                print("PDF generated at:", pdf_path)
            else:
                print("PDF was not generated.")
        except subprocess.CalledProcessError as e:
            print("pdflatex failed!")
            print("stdout:", e.stdout.decode())
            print("stderr:", e.stderr.decode())

if __name__ == "__main__":
    test_pdflatex()