# Generated by Django 5.2.5 on 2025-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recent_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
