# Generated by Django 5.2.7 on 2025-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('progress', 'Progress'), ('safety', 'Safety'), ('quality', 'Quality')], default='progress', max_length=32)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='completed', max_length=32)),
                ('file', models.FileField(upload_to='reports/')),
                ('size', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
